### ISSUE TITLE
DEVELOP 05: Domain Modeling

### ISSUE THREAD

**Issue by jerry914** [SOA-01/WanderWise#27]
## Task

- [x] Update the description of your project
- [x] Create the domain objects you might need
- [x] Develop your Web Application
- [x] Deploy your Web application to Heroku (AWS)

I couldn't find your Heroku Web App URL in the [Google Team Sheet](https://docs.google.com/spreadsheets/d/1in8nvVFMh99L_NCA-PDzP0xR529cWyqTXr9tJljar0M/edit?gid=1890373367#gid=1890373367). Please ensure your application is deployed online. Feel free to ask for assistance on Teams if you encounter any issues.

## Robocop/Code Smell Offenses

N/A

Great progress so far—keep up the good work!

**Comment by soumyaray** [comment]
Please deploy your app to Heroku asap!

**Comment by soumyaray** [comment]
Big issue I think we should discuss: your entities currently don't have any interesting logic, which makes your app look like it just gets data from an API and shows it on screen (too easy an assignment for our class!). Let's please find a time to discuss what your main logic is and what/where it could be.

The two methods you have in your entities right now are not _business logic_, but rather more like _presentation logic_ that belongs in view objects, because they simply represent the entities as strings on screen.

**Comment by Arijus1979** [comment]
@soumyaray Hello, the app has been deployed https://wanderwise-5adb4693c491.herokuapp.com/

As for the logic. Currently, we only have some data analysis logic (historical flight price calculations).

For example, if we search for a flight from LAX to TPE, we save the information to our database for later analysis. For example, we can show the all-time lowest price and an average price for the selected flight.

Please let us know whether that is enough and what we could do to improve it.
